#include "qemu/osdep.h"
#include "qemu/bitops.h"
#include "disas/riscv.h"
#include "disas/riscv-xqci.h"

typedef enum {
    rv_op_qc_addsat = 1,
    rv_op_qc_addusat,
    rv_op_qc_beqi,
    rv_op_qc_bgei,
    rv_op_qc_bgeui,
    rv_op_qc_blti,
    rv_op_qc_bltui,
    rv_op_qc_bnei,
    rv_op_qc_brev32,
    rv_op_qc_c_bexti,
    rv_op_qc_c_bseti,
    rv_op_qc_c_clrint,
    rv_op_qc_c_delay,
    rv_op_qc_c_di,
    rv_op_qc_c_dir,
    rv_op_qc_c_ei,
    rv_op_qc_c_eir,
    rv_op_qc_c_extu,
    rv_op_qc_c_mienter_nest,
    rv_op_qc_c_mienter,
    rv_op_qc_c_mileaveret,
    rv_op_qc_c_mnret,
    rv_op_qc_c_mret,
    rv_op_qc_c_muliadd,
    rv_op_qc_c_mveqz,
    rv_op_qc_c_ptrace,
    rv_op_qc_c_setint,
    rv_op_qc_c_sync,
    rv_op_qc_c_syncr,
    rv_op_qc_c_syncwf,
    rv_op_qc_c_syncwl,
    rv_op_qc_clo,
    rv_op_qc_clrinti,
    rv_op_qc_compress2,
    rv_op_qc_compress3,
    rv_op_qc_csrrwr,
    rv_op_qc_csrrwri,
    rv_op_qc_cto,
    rv_op_qc_e_addai,
    rv_op_qc_e_addi,
    rv_op_qc_e_andai,
    rv_op_qc_e_andi,
    rv_op_qc_e_beqi,
    rv_op_qc_e_bgei,
    rv_op_qc_e_bgeui,
    rv_op_qc_e_blti,
    rv_op_qc_e_bltui,
    rv_op_qc_e_bnei,
    rv_op_qc_e_j,
    rv_op_qc_e_jal,
    rv_op_qc_e_lb,
    rv_op_qc_e_lbu,
    rv_op_qc_e_lh,
    rv_op_qc_e_lhu,
    rv_op_qc_e_li,
    rv_op_qc_e_lw,
    rv_op_qc_e_orai,
    rv_op_qc_e_ori,
    rv_op_qc_e_sb,
    rv_op_qc_e_sh,
    rv_op_qc_e_sw,
    rv_op_qc_e_xorai,
    rv_op_qc_e_xori,
    rv_op_qc_expand2,
    rv_op_qc_expand3,
    rv_op_qc_ext,
    rv_op_qc_extd,
    rv_op_qc_extdpr,
    rv_op_qc_extdprh,
    rv_op_qc_extdr,
    rv_op_qc_extdu,
    rv_op_qc_extdupr,
    rv_op_qc_extduprh,
    rv_op_qc_extdur,
    rv_op_qc_extu,
    rv_op_qc_insb,
    rv_op_qc_insbh,
    rv_op_qc_insbhr,
    rv_op_qc_insbi,
    rv_op_qc_insbpr,
    rv_op_qc_insbprh,
    rv_op_qc_insbr,
    rv_op_qc_insbri,
    rv_op_qc_inw,
    rv_op_qc_li,
    rv_op_qc_lieq,
    rv_op_qc_lieqi,
    rv_op_qc_lige,
    rv_op_qc_ligei,
    rv_op_qc_ligeu,
    rv_op_qc_ligeui,
    rv_op_qc_lilt,
    rv_op_qc_lilti,
    rv_op_qc_liltu,
    rv_op_qc_liltui,
    rv_op_qc_line,
    rv_op_qc_linei,
    rv_op_qc_lrb,
    rv_op_qc_lrbu,
    rv_op_qc_lrh,
    rv_op_qc_lrhu,
    rv_op_qc_lrw,
    rv_op_qc_lwm,
    rv_op_qc_lwmi,
    rv_op_qc_muliadd,
    rv_op_qc_mveq,
    rv_op_qc_mveqi,
    rv_op_qc_mvge,
    rv_op_qc_mvgei,
    rv_op_qc_mvgeu,
    rv_op_qc_mvgeui,
    rv_op_qc_mvlt,
    rv_op_qc_mvlti,
    rv_op_qc_mvltu,
    rv_op_qc_mvltui,
    rv_op_qc_mvne,
    rv_op_qc_mvnei,
    rv_op_qc_norm,
    rv_op_qc_normeu,
    rv_op_qc_normu,
    rv_op_qc_outw,
    rv_op_qc_pcoredump,
    rv_op_qc_pexit,
    rv_op_qc_ppreg,
    rv_op_qc_ppregs,
    rv_op_qc_pputc,
    rv_op_qc_pputci,
    rv_op_qc_pputs,
    rv_op_qc_psyscall,
    rv_op_qc_psyscalli,
    rv_op_qc_selecteqi,
    rv_op_qc_selectieq,
    rv_op_qc_selectieqi,
    rv_op_qc_selectiieq,
    rv_op_qc_selectiine,
    rv_op_qc_selectine,
    rv_op_qc_selectinei,
    rv_op_qc_selectnei,
    rv_op_qc_setinti,
    rv_op_qc_setwm,
    rv_op_qc_setwmi,
    rv_op_qc_shladd,
    rv_op_qc_shlsat,
    rv_op_qc_shlusat,
    rv_op_qc_srb,
    rv_op_qc_srh,
    rv_op_qc_srw,
    rv_op_qc_subsat,
    rv_op_qc_subusat,
    rv_op_qc_swm,
    rv_op_qc_swmi,
    rv_op_qc_sync,
    rv_op_qc_syncr,
    rv_op_qc_syncwf,
    rv_op_qc_syncwl,
    rv_op_qc_wrap,
    rv_op_qc_wrapi,
} rv_xqci_opcode;

const rv_opcode_data xqci_opcode_data[] = {
    { "qc.illegal", rv_codec_illegal, rv_fmt_none, NULL, 0, 0, 0 },
    { "qc.addsat", rv_codec_skip, "O\t0,2,1", NULL, 0, 0, 0 },
    { "qc.addusat", rv_codec_skip, "O\t0,2,1", NULL, 0, 0, 0 },
    { "qc.beqi", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.bgei", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.bgeui", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.blti", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.bltui", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.bnei", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.brev32", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.c.bexti", rv_codec_skip, "O\t0,k", NULL, 0, 0, 0 },
    { "qc.c.bseti", rv_codec_skip, "O\t0,k", NULL, 0, 0, 0 },
    { "qc.c.clrint", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.c.delay", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.c.di", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.dir", rv_codec_skip, "O\t0", NULL, 0, 0, 0 },
    { "qc.c.ei", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.eir", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.c.extu", rv_codec_skip, "O\t0,j", NULL, 0, 0, 0 },
    { "qc.c.mienter.nest", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.mienter", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.mileaveret", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.mnret", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.mret", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.muliadd", rv_codec_skip, "O\t0,1,k", NULL, 0, 0, 0 },
    { "qc.c.mveqz", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.c.ptrace", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.c.setint", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.c.sync", rv_codec_skip, "O\tk", NULL, 0, 0, 0 },
    { "qc.c.syncr", rv_codec_skip, "O\tk", NULL, 0, 0, 0 },
    { "qc.c.syncwf", rv_codec_skip, "O\tk", NULL, 0, 0, 0 },
    { "qc.c.syncwl", rv_codec_skip, "O\tk", NULL, 0, 0, 0 },
    { "qc.clo", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.clrinti", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.compress2", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.compress3", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.csrrwr", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.csrrwri", rv_codec_skip, "O\t0,i,2", NULL, 0, 0, 0 },
    { "qc.cto", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.e.addai", rv_codec_skip, "O\t0,i", NULL, 0, 0, 0 },
    { "qc.e.addi", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.andai", rv_codec_skip, "O\t0,i", NULL, 0, 0, 0 },
    { "qc.e.andi", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.beqi", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.e.bgei", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.e.bgeui", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.e.blti", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.e.bltui", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.e.bnei", rv_codec_skip, "O\t1,i,Z", NULL, 0, 0, 0 },
    { "qc.e.j", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.e.jal", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.e.lb", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.lbu", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.lh", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.lhu", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.li", rv_codec_skip, "O\t0,i", NULL, 0, 0, 0 },
    { "qc.e.lw", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.orai", rv_codec_skip, "O\t0,i", NULL, 0, 0, 0 },
    { "qc.e.ori", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.e.sb", rv_codec_skip, "O\t1,2,i", NULL, 0, 0, 0 },
    { "qc.e.sh", rv_codec_skip, "O\t1,2,i", NULL, 0, 0, 0 },
    { "qc.e.sw", rv_codec_skip, "O\t1,2,i", NULL, 0, 0, 0 },
    { "qc.e.xorai", rv_codec_skip, "O\t0,i", NULL, 0, 0, 0 },
    { "qc.e.xori", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.expand2", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.expand3", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.ext", rv_codec_skip, "O\t0,1,k,j", NULL, 0, 0, 0 },
    { "qc.extd", rv_codec_skip, "O\t0,1,k,j", NULL, 0, 0, 0 },
    { "qc.extdpr", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.extdprh", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.extdr", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.extdu", rv_codec_skip, "O\t0,1,k,j", NULL, 0, 0, 0 },
    { "qc.extdupr", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.extduprh", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.extdur", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.extu", rv_codec_skip, "O\t0,1,k,j", NULL, 0, 0, 0 },
    { "qc.insb", rv_codec_skip, "O\t0,1,k,j", NULL, 0, 0, 0 },
    { "qc.insbh", rv_codec_skip, "O\t0,1,k,j", NULL, 0, 0, 0 },
    { "qc.insbhr", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.insbi", rv_codec_skip, "O\t0,i,k,j", NULL, 0, 0, 0 },
    { "qc.insbpr", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.insbprh", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.insbr", rv_codec_skip, "O\t0,1,2", NULL, 0, 0, 0 },
    { "qc.insbri", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.inw", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.li", rv_codec_skip, "O\t0,i", NULL, 0, 0, 0 },
    { "qc.lieq", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.lieqi", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.lige", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.ligei", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.ligeu", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.ligeui", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.lilt", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.lilti", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.liltu", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.liltui", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.line", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.linei", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.lrb", rv_codec_skip, "O\t0,2,1,k", NULL, 0, 0, 0 },
    { "qc.lrbu", rv_codec_skip, "O\t0,2,1,k", NULL, 0, 0, 0 },
    { "qc.lrh", rv_codec_skip, "O\t0,2,1,k", NULL, 0, 0, 0 },
    { "qc.lrhu", rv_codec_skip, "O\t0,2,1,k", NULL, 0, 0, 0 },
    { "qc.lrw", rv_codec_skip, "O\t0,2,1,k", NULL, 0, 0, 0 },
    { "qc.lwm", rv_codec_skip, "O\t0,2,1,i", NULL, 0, 0, 0 },
    { "qc.lwmi", rv_codec_skip, "O\t0,j,1,i", NULL, 0, 0, 0 },
    { "qc.muliadd", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
    { "qc.mveq", rv_codec_skip, "O\t0,6,2,1", NULL, 0, 0, 0 },
    { "qc.mveqi", rv_codec_skip, "O\t0,6,i,1", NULL, 0, 0, 0 },
    { "qc.mvge", rv_codec_skip, "O\t0,6,2,1", NULL, 0, 0, 0 },
    { "qc.mvgei", rv_codec_skip, "O\t0,6,i,1", NULL, 0, 0, 0 },
    { "qc.mvgeu", rv_codec_skip, "O\t0,6,2,1", NULL, 0, 0, 0 },
    { "qc.mvgeui", rv_codec_skip, "O\t0,6,i,1", NULL, 0, 0, 0 },
    { "qc.mvlt", rv_codec_skip, "O\t0,6,2,1", NULL, 0, 0, 0 },
    { "qc.mvlti", rv_codec_skip, "O\t0,6,i,1", NULL, 0, 0, 0 },
    { "qc.mvltu", rv_codec_skip, "O\t0,6,2,1", NULL, 0, 0, 0 },
    { "qc.mvltui", rv_codec_skip, "O\t0,6,i,1", NULL, 0, 0, 0 },
    { "qc.mvne", rv_codec_skip, "O\t0,6,2,1", NULL, 0, 0, 0 },
    { "qc.mvnei", rv_codec_skip, "O\t0,6,i,1", NULL, 0, 0, 0 },
    { "qc.norm", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.normeu", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.normu", rv_codec_skip, "O\t0,1", NULL, 0, 0, 0 },
    { "qc.outw", rv_codec_skip, "O\t2,1,i", NULL, 0, 0, 0 },
    { "qc.pcoredump", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.pexit", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.ppreg", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.ppregs", rv_codec_skip, "O\t", NULL, 0, 0, 0 },
    { "qc.pputc", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.pputci", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.pputs", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.psyscall", rv_codec_skip, "O\t1", NULL, 0, 0, 0 },
    { "qc.psyscalli", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.selecteqi", rv_codec_skip, "O\t0,6,2,i", NULL, 0, 0, 0 },
    { "qc.selectieq", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.selectieqi", rv_codec_skip, "O\t0,j,2,i", NULL, 0, 0, 0 },
    { "qc.selectiieq", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.selectiine", rv_codec_skip, "O\t0,j,i,1", NULL, 0, 0, 0 },
    { "qc.selectine", rv_codec_skip, "O\t0,j,2,1", NULL, 0, 0, 0 },
    { "qc.selectinei", rv_codec_skip, "O\t0,j,2,i", NULL, 0, 0, 0 },
    { "qc.selectnei", rv_codec_skip, "O\t0,6,2,i", NULL, 0, 0, 0 },
    { "qc.setinti", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.setwm", rv_codec_skip, "O\t6,2,1,i", NULL, 0, 0, 0 },
    { "qc.setwmi", rv_codec_skip, "O\t6,j,1,i", NULL, 0, 0, 0 },
    { "qc.shladd", rv_codec_skip, "O\t0,1,2,k", NULL, 0, 0, 0 },
    { "qc.shlsat", rv_codec_skip, "O\t0,2,1", NULL, 0, 0, 0 },
    { "qc.shlusat", rv_codec_skip, "O\t0,2,1", NULL, 0, 0, 0 },
    { "qc.srb", rv_codec_skip, "O\t6,2,1,k", NULL, 0, 0, 0 },
    { "qc.srh", rv_codec_skip, "O\t6,2,1,k", NULL, 0, 0, 0 },
    { "qc.srw", rv_codec_skip, "O\t6,2,1,k", NULL, 0, 0, 0 },
    { "qc.subsat", rv_codec_skip, "O\t0,2,1", NULL, 0, 0, 0 },
    { "qc.subusat", rv_codec_skip, "O\t0,2,1", NULL, 0, 0, 0 },
    { "qc.swm", rv_codec_skip, "O\t6,2,1,i", NULL, 0, 0, 0 },
    { "qc.swmi", rv_codec_skip, "O\t6,j,1,i", NULL, 0, 0, 0 },
    { "qc.sync", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.syncr", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.syncwf", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.syncwl", rv_codec_skip, "O\ti", NULL, 0, 0, 0 },
    { "qc.wrap", rv_codec_skip, "O\t0,2,1", NULL, 0, 0, 0 },
    { "qc.wrapi", rv_codec_skip, "O\t0,1,i", NULL, 0, 0, 0 },
};

static uint64_t decode_xqci_48_impl_load_bytes(rv_decode *dec, uint64_t insn, int offset, int length)
{
    return 0;
}
#include "riscv-xqci-16-decode.c.inc"
#include "riscv-xqci-32-decode.c.inc"
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#include "riscv-xqci-48-decode.c.inc"
#pragma GCC diagnostic pop
#include "riscv-xqci-trans-disas.c.inc"

void decode_xqci(rv_decode *dec, rv_isa isa) {
    rv_inst inst = dec->inst;
    dec->op = rv_op_illegal;
    switch (dec->inst_length) {
    case 2:
        decode_xqci_16_impl(dec, inst);
        break;
    case 4:
        decode_xqci_32_impl(dec, inst);
        break;
    case 6:
        inst <<= (64-48);
        decode_xqci_48_impl(dec, inst);
        break;
    }
}
