SRC=$(SRC_PATH)/tests/tcg/riscv32

XQCI_KLEE_IO_DIR=$(SRC)/klee_io/xqci
XQCI_OUT_ASM_DIR=xqci-asm-tests
XQCI_OUT_C_DIR=xqci-c-tests
XQCI_OUT_C_CODE_DIR:=$(XQCI_OUT_C_DIR)/code
XQCI_OUT_C_BIN_DIR:=$(XQCI_OUT_C_DIR)/bin
XQCI_INST_DIR=$(SRC)/Xqci

XQCCMP_KLEE_IO_DIR=$(SRC)/klee_io/xqccmp
XQCCMP_OUT_ASM_DIR=xqccmp-asm-tests
XQCCMP_OUT_C_DIR=xqccmp-c-tests
XQCCMP_OUT_C_CODE_DIR:=$(XQCCMP_OUT_C_DIR)/code
XQCCMP_OUT_C_BIN_DIR:=$(XQCCMP_OUT_C_DIR)/bin
XQCCMP_INST_DIR=$(SRC)/Xqccmp

SMRNMI_KLEE_IO_DIR=$(SRC)/klee_io/smrnmi
SMRNMI_OUT_ASM_DIR=smrnmi-asm-tests
SMRNMI_OUT_C_DIR=smrnmi-c-tests
SMRNMI_OUT_C_CODE_DIR:=$(SMRNMI_OUT_C_DIR)/code
SMRNMI_OUT_C_BIN_DIR:=$(SMRNMI_OUT_C_DIR)/bin
SMRNMI_INST_DIR=$(SRC)/Smrnmi

CFLAGS=-fuse-ld=qcld -T $(SRC)/mem-test-page.ld --target=riscv32-unknown-linux-gnu -nostdlib -static -menable-experimental-extensions

QEMU=./qemu-riscv32

# These tests are a bit annoying to run in a makefile since any given input yaml file
# in $(KLEE_IO_DIR)/* can generate multiple tests

.PHONY: build-xqci-asm-tests
build-xqci-asm-tests:
	mkdir -p $(XQCI_OUT_ASM_DIR)
	@for in_io in $(XQCI_KLEE_IO_DIR)/*; do \
		instname=$$(basename $$in_io); \
		echo "Building tests for" $$instname; \
		python $(SRC)/assemble.py --inst-dir $(XQCI_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(XQCI_OUT_ASM_DIR)/$$instname; \
	done
	chmod +x $(XQCI_OUT_ASM_DIR)/*

.PHONY: run-xqci-asm-tests
run-xqci-asm-tests: $(XQCI_OUT_ASM_DIR)/*
	@for exe in $(XQCI_OUT_ASM_DIR)/*; do \
		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
		err=$$?; \
		if [ $$err -eq 0 ]; then \
			echo "PASS" $$exe; \
		else \
			echo "FAIL ($${err}) $${exe}"; \
		fi; \
	done

.PHONY: build-xqccmp-asm-tests
build-xqccmp-asm-tests:
	mkdir -p $(XQCCMP_OUT_ASM_DIR)
	@for in_io in $(XQCCMP_KLEE_IO_DIR)/*; do \
		instname=$$(basename $$in_io); \
		echo "Building tests for" $$instname; \
		python $(SRC)/assemble.py --inst-dir $(XQCCMP_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(XQCCMP_OUT_ASM_DIR)/$$instname; \
	done
	chmod +x $(XQCCMP_OUT_ASM_DIR)/*

.PHONY: run-xqccmp-asm-tests
run-xqccmp-asm-tests: $(XQCCMP_OUT_ASM_DIR)/*
	@for exe in $(XQCCMP_OUT_ASM_DIR)/*; do \
		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
		err=$$?; \
		if [ $$err -eq 0 ]; then \
			echo "PASS" $$exe; \
		else \
			echo "FAIL ($${err}) $${exe}"; \
		fi; \
	done

.PHONY: build-smrnmi-asm-tests
build-smrnmi-asm-tests:
	mkdir -p $(SMRNMI_OUT_ASM_DIR)
	@for in_io in $(SMRNMI_KLEE_IO_DIR)/*; do \
		instname=$$(basename $$in_io); \
		echo "Building tests for" $$instname; \
		python $(SRC)/assemble.py --inst-dir $(SMRNMI_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(SMRNMI_OUT_ASM_DIR)/$$instname; \
	done
	chmod +x $(SMRNMI_OUT_ASM_DIR)/*

.PHONY: run-smrnmi-asm-tests
run-smrnmi-asm-tests: $(SMRNMI_OUT_ASM_DIR)/*
	@for exe in $(SMRNMI_OUT_ASM_DIR)/*; do \
		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
		err=$$?; \
		if [ $$err -eq 0 ]; then \
			echo "PASS" $$exe; \
		else \
			echo "FAIL ($${err}) $${exe}"; \
		fi; \
	done

.PHONY: build-xqci-c-tests-dir
build-xqci-c-tests-dir:
	mkdir -p $(XQCI_OUT_C_DIR)
	mkdir -p $(XQCI_OUT_C_CODE_DIR)
	mkdir -p $(XQCI_OUT_C_BIN_DIR)

.PHONY: build-xqccmp-c-tests-dir
build-xqccmp-c-tests-dir:
	mkdir -p $(XQCCMP_OUT_C_DIR)
	mkdir -p $(XQCCMP_OUT_C_CODE_DIR)
	mkdir -p $(XQCCMP_OUT_C_BIN_DIR)

.PHONY: build-smrnmi-c-tests-dir
build-smrnmi-c-tests-dir:
	mkdir -p $(SMRNMI_OUT_C_DIR)
	mkdir -p $(SMRNMI_OUT_C_CODE_DIR)
	mkdir -p $(SMRNMI_OUT_C_BIN_DIR)

.PHONY: build-xqci-c-tests-code
build-xqci-c-tests-code: build-xqci-c-tests-dir
	@for in_io in $(XQCI_KLEE_IO_DIR)/*; do \
		instname=$$(basename $$in_io); \
		echo "Generating C code for" $$instname; \
		python $(SRC)/c.py --inst-dir $(XQCI_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(XQCI_OUT_C_CODE_DIR)/$$instname.c; \
	done

.PHONY: build-xqci-c-tests
build-xqci-c-tests: build-xqci-c-tests-code
	@for file in $(XQCI_OUT_C_CODE_DIR)/*; do \
		instname=$$(basename $$file); \
		echo "Building test for" $$instname; \
		$(CC) $(CFLAGS) -march=rv32imc_xqci -o $(XQCI_OUT_C_BIN_DIR)/$$instname $$file; \
	done

.PHONY: run-xqci-c-tests
run-xqci-c-tests: $(XQCI_OUT_C_BIN_DIR)/*
	@for exe in $(XQCI_OUT_C_BIN_DIR)/*; do \
		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
		err=$$?; \
		if [ $$err -eq 0 ]; then \
			echo "PASS" $$exe; \
		else \
			echo "FAIL ($${err}) $${exe}"; \
		fi; \
	done






.PHONY: build-xqccmp-c-tests-code
build-xqccmp-c-tests-code: build-xqccmp-c-tests-dir
	@for in_io in $(XQCCMP_KLEE_IO_DIR)/*; do \
		instname=$$(basename $$in_io); \
		echo "Generating C code for" $$instname; \
		python $(SRC)/c.py --inst-dir $(XQCCMP_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(XQCCMP_OUT_C_CODE_DIR)/$$instname.c; \
	done

.PHONY: build-xqccmp-c-tests
build-xqccmp-c-tests: build-xqccmp-c-tests-code
	@for file in $(XQCCMP_OUT_C_CODE_DIR)/*; do \
		instname=$$(basename $$file); \
		echo "Building test for" $$instname; \
		$(CC) $(CFLAGS) -march=rv32imc_xqccmp0p1 -o $(XQCCMP_OUT_C_BIN_DIR)/$$instname $$file; \
	done

.PHONY: run-xqccmp-c-tests
run-xqccmp-c-tests: $(XQCCMP_OUT_C_BIN_DIR)/*
	@for exe in $(XQCCMP_OUT_C_BIN_DIR)/*; do \
		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
		err=$$?; \
		if [ $$err -eq 0 ]; then \
			echo "PASS" $$exe; \
		else \
			echo "FAIL ($${err}) $${exe}"; \
		fi; \
	done





.PHONY: build-smrnmi-c-tests-code
build-smrnmi-c-tests-code: build-smrnmi-c-tests-dir
	@for in_io in $(SMRNMI_KLEE_IO_DIR)/*; do \
		instname=$$(basename $$in_io); \
		echo "Generating C code for" $$instname; \
		python $(SRC)/c.py --inst-dir $(SMRNMI_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(SMRNMI_OUT_C_CODE_DIR)/$$instname.c; \
	done

.PHONY: build-smrnmi-c-tests
build-smrnmi-c-tests: build-smrnmi-c-tests-code
	@for file in $(SMRNMI_OUT_C_CODE_DIR)/*; do \
		instname=$$(basename $$file); \
		echo "Building test for" $$instname; \
		$(CC) $(CFLAGS) -march=rv32imc_smrnmi -o $(SMRNMI_OUT_C_BIN_DIR)/$$instname $$file; \
	done

.PHONY: run-smrnmi-c-tests
run-smrnmi-c-tests: $(SMRNMI_OUT_C_BIN_DIR)/*
	@for exe in $(SMRNMI_OUT_C_BIN_DIR)/*; do \
		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
		err=$$?; \
		if [ $$err -eq 0 ]; then \
			echo "PASS" $$exe; \
		else \
			echo "FAIL ($${err}) $${exe}"; \
		fi; \
	done
